/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AuthenticatedSellerStorefrontRouteImport } from './routes/_authenticated/seller/storefront'
import { Route as AuthenticatedSellerDashboardRouteImport } from './routes/_authenticated/seller/dashboard'
import { Route as AuthenticatedBuyerHomeRouteImport } from './routes/_authenticated/buyer/home'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellerStorefrontRoute =
  AuthenticatedSellerStorefrontRouteImport.update({
    id: '/seller/storefront',
    path: '/seller/storefront',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerDashboardRoute =
  AuthenticatedSellerDashboardRouteImport.update({
    id: '/seller/dashboard',
    path: '/seller/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyerHomeRoute = AuthenticatedBuyerHomeRouteImport.update({
  id: '/buyer/home',
  path: '/buyer/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/store/$slug': typeof StoreSlugRoute
  '/buyer/home': typeof AuthenticatedBuyerHomeRoute
  '/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/store/$slug': typeof StoreSlugRoute
  '/buyer/home': typeof AuthenticatedBuyerHomeRoute
  '/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/store/$slug': typeof StoreSlugRoute
  '/_authenticated/buyer/home': typeof AuthenticatedBuyerHomeRoute
  '/_authenticated/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/_authenticated/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/store/$slug'
    | '/buyer/home'
    | '/seller/dashboard'
    | '/seller/storefront'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/store/$slug'
    | '/buyer/home'
    | '/seller/dashboard'
    | '/seller/storefront'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/store/$slug'
    | '/_authenticated/buyer/home'
    | '/_authenticated/seller/dashboard'
    | '/_authenticated/seller/storefront'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller/storefront': {
      id: '/_authenticated/seller/storefront'
      path: '/seller/storefront'
      fullPath: '/seller/storefront'
      preLoaderRoute: typeof AuthenticatedSellerStorefrontRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/dashboard': {
      id: '/_authenticated/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof AuthenticatedSellerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer/home': {
      id: '/_authenticated/buyer/home'
      path: '/buyer/home'
      fullPath: '/buyer/home'
      preLoaderRoute: typeof AuthenticatedBuyerHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuyerHomeRoute: typeof AuthenticatedBuyerHomeRoute
  AuthenticatedSellerDashboardRoute: typeof AuthenticatedSellerDashboardRoute
  AuthenticatedSellerStorefrontRoute: typeof AuthenticatedSellerStorefrontRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuyerHomeRoute: AuthenticatedBuyerHomeRoute,
  AuthenticatedSellerDashboardRoute: AuthenticatedSellerDashboardRoute,
  AuthenticatedSellerStorefrontRoute: AuthenticatedSellerStorefrontRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
