/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AuthenticatedSellerRouteRouteImport } from './routes/_authenticated/seller/route'
import { Route as AuthenticatedSellerVerificationRouteImport } from './routes/_authenticated/seller/verification'
import { Route as AuthenticatedSellerStorefrontRouteImport } from './routes/_authenticated/seller/storefront'
import { Route as AuthenticatedSellerSettingsRouteImport } from './routes/_authenticated/seller/settings'
import { Route as AuthenticatedSellerOrdersRouteImport } from './routes/_authenticated/seller/orders'
import { Route as AuthenticatedSellerDashboardRouteImport } from './routes/_authenticated/seller/dashboard'
import { Route as AuthenticatedBuyerHomeRouteImport } from './routes/_authenticated/buyer/home'
import { Route as AuthenticatedSellerProductsIndexRouteImport } from './routes/_authenticated/seller/products/index'
import { Route as AuthenticatedSellerProductsNewRouteImport } from './routes/_authenticated/seller/products/new'
import { Route as AuthenticatedSellerProductsIdRouteImport } from './routes/_authenticated/seller/products/$id'

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellerRouteRoute =
  AuthenticatedSellerRouteRouteImport.update({
    id: '/seller',
    path: '/seller',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerVerificationRoute =
  AuthenticatedSellerVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerStorefrontRoute =
  AuthenticatedSellerStorefrontRouteImport.update({
    id: '/storefront',
    path: '/storefront',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerSettingsRoute =
  AuthenticatedSellerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerOrdersRoute =
  AuthenticatedSellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerDashboardRoute =
  AuthenticatedSellerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedBuyerHomeRoute = AuthenticatedBuyerHomeRouteImport.update({
  id: '/buyer/home',
  path: '/buyer/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerProductsIndexRoute =
  AuthenticatedSellerProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerProductsNewRoute =
  AuthenticatedSellerProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)
const AuthenticatedSellerProductsIdRoute =
  AuthenticatedSellerProductsIdRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedSellerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/seller': typeof AuthenticatedSellerRouteRouteWithChildren
  '/store/$slug': typeof StoreSlugRoute
  '/buyer/home': typeof AuthenticatedBuyerHomeRoute
  '/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
  '/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/seller/products/$id': typeof AuthenticatedSellerProductsIdRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
  '/seller/products/': typeof AuthenticatedSellerProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/seller': typeof AuthenticatedSellerRouteRouteWithChildren
  '/store/$slug': typeof StoreSlugRoute
  '/buyer/home': typeof AuthenticatedBuyerHomeRoute
  '/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
  '/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/seller/products/$id': typeof AuthenticatedSellerProductsIdRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
  '/seller/products': typeof AuthenticatedSellerProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteRouteWithChildren
  '/store/$slug': typeof StoreSlugRoute
  '/_authenticated/buyer/home': typeof AuthenticatedBuyerHomeRoute
  '/_authenticated/seller/dashboard': typeof AuthenticatedSellerDashboardRoute
  '/_authenticated/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/_authenticated/seller/settings': typeof AuthenticatedSellerSettingsRoute
  '/_authenticated/seller/storefront': typeof AuthenticatedSellerStorefrontRoute
  '/_authenticated/seller/verification': typeof AuthenticatedSellerVerificationRoute
  '/_authenticated/seller/products/$id': typeof AuthenticatedSellerProductsIdRoute
  '/_authenticated/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
  '/_authenticated/seller/products/': typeof AuthenticatedSellerProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/marketplace'
    | '/seller'
    | '/store/$slug'
    | '/buyer/home'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/seller/settings'
    | '/seller/storefront'
    | '/seller/verification'
    | '/seller/products/$id'
    | '/seller/products/new'
    | '/seller/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/marketplace'
    | '/seller'
    | '/store/$slug'
    | '/buyer/home'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/seller/settings'
    | '/seller/storefront'
    | '/seller/verification'
    | '/seller/products/$id'
    | '/seller/products/new'
    | '/seller/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/marketplace'
    | '/_authenticated/seller'
    | '/store/$slug'
    | '/_authenticated/buyer/home'
    | '/_authenticated/seller/dashboard'
    | '/_authenticated/seller/orders'
    | '/_authenticated/seller/settings'
    | '/_authenticated/seller/storefront'
    | '/_authenticated/seller/verification'
    | '/_authenticated/seller/products/$id'
    | '/_authenticated/seller/products/new'
    | '/_authenticated/seller/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/verification': {
      id: '/_authenticated/seller/verification'
      path: '/verification'
      fullPath: '/seller/verification'
      preLoaderRoute: typeof AuthenticatedSellerVerificationRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/storefront': {
      id: '/_authenticated/seller/storefront'
      path: '/storefront'
      fullPath: '/seller/storefront'
      preLoaderRoute: typeof AuthenticatedSellerStorefrontRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/settings': {
      id: '/_authenticated/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof AuthenticatedSellerSettingsRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/orders': {
      id: '/_authenticated/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AuthenticatedSellerOrdersRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/dashboard': {
      id: '/_authenticated/seller/dashboard'
      path: '/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof AuthenticatedSellerDashboardRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/buyer/home': {
      id: '/_authenticated/buyer/home'
      path: '/buyer/home'
      fullPath: '/buyer/home'
      preLoaderRoute: typeof AuthenticatedBuyerHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/products/': {
      id: '/_authenticated/seller/products/'
      path: '/products'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof AuthenticatedSellerProductsIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/products/new': {
      id: '/_authenticated/seller/products/new'
      path: '/products/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof AuthenticatedSellerProductsNewRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
    '/_authenticated/seller/products/$id': {
      id: '/_authenticated/seller/products/$id'
      path: '/products/$id'
      fullPath: '/seller/products/$id'
      preLoaderRoute: typeof AuthenticatedSellerProductsIdRouteImport
      parentRoute: typeof AuthenticatedSellerRouteRoute
    }
  }
}

interface AuthenticatedSellerRouteRouteChildren {
  AuthenticatedSellerDashboardRoute: typeof AuthenticatedSellerDashboardRoute
  AuthenticatedSellerOrdersRoute: typeof AuthenticatedSellerOrdersRoute
  AuthenticatedSellerSettingsRoute: typeof AuthenticatedSellerSettingsRoute
  AuthenticatedSellerStorefrontRoute: typeof AuthenticatedSellerStorefrontRoute
  AuthenticatedSellerVerificationRoute: typeof AuthenticatedSellerVerificationRoute
  AuthenticatedSellerProductsIdRoute: typeof AuthenticatedSellerProductsIdRoute
  AuthenticatedSellerProductsNewRoute: typeof AuthenticatedSellerProductsNewRoute
  AuthenticatedSellerProductsIndexRoute: typeof AuthenticatedSellerProductsIndexRoute
}

const AuthenticatedSellerRouteRouteChildren: AuthenticatedSellerRouteRouteChildren =
  {
    AuthenticatedSellerDashboardRoute: AuthenticatedSellerDashboardRoute,
    AuthenticatedSellerOrdersRoute: AuthenticatedSellerOrdersRoute,
    AuthenticatedSellerSettingsRoute: AuthenticatedSellerSettingsRoute,
    AuthenticatedSellerStorefrontRoute: AuthenticatedSellerStorefrontRoute,
    AuthenticatedSellerVerificationRoute: AuthenticatedSellerVerificationRoute,
    AuthenticatedSellerProductsIdRoute: AuthenticatedSellerProductsIdRoute,
    AuthenticatedSellerProductsNewRoute: AuthenticatedSellerProductsNewRoute,
    AuthenticatedSellerProductsIndexRoute:
      AuthenticatedSellerProductsIndexRoute,
  }

const AuthenticatedSellerRouteRouteWithChildren =
  AuthenticatedSellerRouteRoute._addFileChildren(
    AuthenticatedSellerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSellerRouteRoute: typeof AuthenticatedSellerRouteRouteWithChildren
  AuthenticatedBuyerHomeRoute: typeof AuthenticatedBuyerHomeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSellerRouteRoute: AuthenticatedSellerRouteRouteWithChildren,
  AuthenticatedBuyerHomeRoute: AuthenticatedBuyerHomeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MarketplaceRoute: MarketplaceRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
